In [1]:
%matplotlib inline

# Tensor张量
张量是一种特殊的数据结构，与数组和矩阵非常相似。
在PyTorch中，我们使用张量对模型的输入和输出以及模型的参数进行编码。

张量类似于NumPy 的ndarray，除了张量可以在 GPU 或其他件加速器上运行。
事实上，张量和NumPy 数组通常可以共享相同的底层内存，从而无需复制数据(请参阅Bridge with NumPy)。张量也针对自动微分进行了优化（我们将在稍后的Autograd 部分中看到更多相关内容）。
如果您熟悉ndarrays，那么您对 ​​Tensor API 会很熟悉。如果没有，请跟随！

In [2]:
import torch
import numpy as np

初始化张量
Tensors can be initialized in various ways. Take a look at the following examples:

**Directly from data**

Tensors can be created directly from data. The data type is automatically inferred.

In [3]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

来自 NumPy 数组

张量可以从 NumPy 数组创建（反之亦然 - 请参阅bridge-to-np-label）。

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

**从另一个张量：**

新张量保留参数张量的属性（形状、数据类型），除非显式覆盖。

In [5]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor:\n {x_ones} \n")

Ones Tensor:
 tensor([[1, 1],
        [1, 1]]) 



In [6]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor:\n {x_rand} \n")

Random Tensor:
 tensor([[0.4159, 0.0166],
        [0.9493, 0.8862]]) 



使用随机或恒定值：

shape是张量维度的元组。在下面的函数中，它决定了输出张量的维度。

In [7]:
shape = (2,3)
rand_tensor = torch.rand(shape)
one_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor:\n {rand_tensor} \n")
print(f"Ones Tensor:\n {one_tensor} \n")
print(f"Zeros Tensor:\n {zeros_tensor}")

Random Tensor:
 tensor([[0.0069, 0.0230, 0.5117],
        [0.0420, 0.7725, 0.5484]]) 

Ones Tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


Attributes of a Tensor

Tensor attributes describe their shape, datatype, and the device on which they are stored.

In [8]:
tensor = torch.rand(2,3)
print(f"Shape of tensor:{tensor.shape}")
print(f"Datatype of tensor:{tensor.dtype}")
print(f"Device tensor is stored on:{tensor.device}")

Shape of tensor:torch.Size([2, 3])
Datatype of tensor:torch.float32
Device tensor is stored on:cpu


Operations on Tensors
Over 100 tensor operations, including arithmetic, linear algebra, matrix manipulation (transposing,
                                                                                       indexing, slicing), sampling and more are
comprehensively described `here <https://pytorch.org/docs/stable/torch.html>`__.

Each of these operations can be run on the GPU (at typically higher speeds than on a
CPU). If you’re using Colab, allocate a GPU by going to Runtime > Change runtime type > GPU.

By default, tensors are created on the CPU. We need to explicitly move tensors to the GPU using
``.to`` method (after checking for GPU availability). Keep in mind that copying large tensors
across devices can be expensive in terms of time and memory!


In [9]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

/home/linxu/Apps/Anaconda3/envs/jupyter/lib/python3.7/site-packages/torch/cuda/__init__.py:145: UserWarning: 
NVIDIA GeForce RTX 3060 Laptop GPU with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
If you want to use the NVIDIA GeForce RTX 3060 Laptop GPU GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))


Standard numpy-like indexing and slicing:

In [10]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


连接张量您可以用来torch.cat沿给定维度连接一系列张量。另请参见torch.stack <https://pytorch.org/docs/stable/generated/torch.stack.html>__，另一个加入 op 的张量与torch.cat.

In [ ]:
t1 = torch.cat([tensor, tensor, tensor], dim =1)
print(t1)

In [ ]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)